### PR TITLE
Update: Change log_reference_length to log_reference_params

### PR DESCRIPTION
**Pull request by 3m1n3nc3**
This pull request allows passing additional parameters to the log reference generator.

### CODE REVIEW

**Comment by HPWebdeveloper** [comment]
Please open the access then I can modify some comments :)

**Comment by 3m1n3nc3** [comment]
> Please open the access then I can modify some comments :)

How do I do that?

**Comment by HPWebdeveloper** [comment]
> > Please open the access then I can modify some comments :)
> 
> How do I do that?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by 3m1n3nc3** [comment]
> > > Please open the access then I can modify some comments :)
> > 
> > 
> > How do I do that?
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> edit the existing pull request to enable maintainer access.
> 
> Enable Edit Access: On the right-hand side of the pull request page, you should look for the checkbox labeled "Allow edits from maintainers." If it's not already checked, you need to check this box.

image
The option appears to be missing here

**Comment by HPWebdeveloper** [comment]
Ok,

**Comment by 3m1n3nc3** [comment]
> Ok,

Is there something else I can do?

**Pull request merged**
