### PR TITLE
Adds support for restricted wallets and description for logs and improve overall type annotations.

### PR DESCRIPTION
**Pull request by 3m1n3nc3**
See [Issue #8](https://github.com/HPWebdeveloper/laravel-pay-pocket/issues/8)

### CODE REVIEW

**Comment by HPWebdeveloper** [comment]
This pull request attempts to address two distinct areas: enhancing type annotations and introducing a new feature. These concerns are sufficiently separate to warrant individual pull requests. Therefore, it is required you create two distinct pull requests. 

Regarding the feature-related pull request, it's imperative to adhere to two crucial requirements. Firstly, provide a comprehensive explanation of the feature's functionality and its applicable use cases. Secondly, ensure that tests are written to cover all conceivable new scenarios thoroughly.

Your contribution is greatly valued, and these steps will enhance the clarity and effectiveness of the project. 

Thank you for contributing.

**Comment by 3m1n3nc3** [comment]
I opened a new pull request that contains a few more changes and tests, [#10](https://github.com/HPWebdeveloper/laravel-pay-pocket/pull/10)

**Comment by HPWebdeveloper** [comment]
@3m1n3nc3 

There are some PHPDocs you have previously add/corrected/modifed in this closed PR

https://github.com/HPWebdeveloper/laravel-pay-pocket/pull/9/files

You can now bring them as a separate PR.

**Comment by 3m1n3nc3** [comment]
> @3m1n3nc3
> 
> There are some PHPDocs you have previously add/corrected/modifed in this closed PR
> 
> https://github.com/HPWebdeveloper/laravel-pay-pocket/pull/9/files
> 
> You can now bring them as a separate PR.

Can we start with the restricted wallet feature?

**Comment by HPWebdeveloper** [comment]
@3m1n3nc3 

have you checked my questions mentioned here?

Please explain and let me know the use case you have experienced.

https://github.com/HPWebdeveloper/laravel-pay-pocket/issues/8

Thanks

**Comment by HPWebdeveloper** [comment]
@3m1n3nc3 

can you bring all types correction you previously did and PHPDoc blocks like these as a **separate** PR?

```php

interface WalletOperations
{
    /**
     * Get User's Wallet Balance
     *
     * @return int|float
     */
    public function getWalletBalanceAttribute(): int|float;

    /**
     * Get the balance of a specific wallet type.
     *
     *
     * @param string $walletType
     *
     * @return float|int
     */
    public function getWalletBalanceByType(string $walletType): float|int;

    /**
     *  Check if User's wallet balance is more than given value
     *
     * @param int|float $value
     *
     * @return bool
     */
    public function hasSufficientBalance(int|float $value): bool;
    
    ```

**Comment by 3m1n3nc3** [comment]
> @3m1n3nc3
> 
> can you bring all types correction you previously did and PHPDoc blocks like these as a **separate** PR?
> 
> these are examples, I saw you have corrected also some type hints. please bring them as well in a single PR.
> 
> ```
> interface WalletOperations
> {
>     /**
>      * Get User's Wallet Balance
>      *
>      * @return int|float
>      */
>     public function getWalletBalanceAttribute(): int|float;
> 
>     /**
>      * Get the balance of a specific wallet type.
>      *
>      *
>      * @param string $walletType
>      *
>      * @return float|int
>      */
>     public function getWalletBalanceByType(string $walletType): float|int;
> 
>     /**
>      *  Check if User's wallet balance is more than given value
>      *
>      * @param int|float $value
>      *
>      * @return bool
>      */
>     public function hasSufficientBalance(int|float $value): bool;
>     
>     ```
> ```

Should the PR contain any code reference to #12 or should be based off the current state of the main branch?

**Comment by HPWebdeveloper** [comment]
The new PR (let's say PR-types) should be pure and independent of any other features.

Make a new branch from the current Main branch.

Please don't add any new code. Just bring those types and phpdocs that you have already coded in this closed PR and not add more.

Regarding the new feature (allowed wallets) we will discuss in another open issues/PR.

**Comment by 3m1n3nc3** [comment]
> The new PR (let's say PR-types) should be pure and independent of any other features.
> 
> Make a new branch from the current Main branch.
> 
> Please don't add any new code. Just bring those types and phpdocs that you have already coded in this closed PR and not add more.
> 
> Regarding the new feature (allowed wallets) we will discuss in another open issues/PR.

@HPWebdeveloper see #13

**Pull request closed without merging**
